version: '3.9'

services:
  inventorymanagement.api:
    build:
      context: .
      dockerfile: src/Adapters/Primary/InventoryManagement.Api/Dockerfile
    container_name: inventorymanagement.api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=InventoryManagementDb;User Id=sa;Password=Test@@123123;TrustServerCertificate=True;"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: inventorymanagement.sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test@@123123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: